### PR TITLE
Update for the current Freenet and WoT versions

### PR DESCRIPTION
**Pull request by gckrol**

### CODE REVIEW

**Comment by Thynix** [comment]
Thanks for writing this! Does "current" mean build 14+ of WoT and a
purge-db4o/1468 prerelease?

**Comment by gerard-** [comment]
No, it builds with the master branches of Fred and plugin-WebOfTrust. I'm not sure about what other branches to use.

**Comment by xor-freenet** [comment]
Thanks for writing this!
Will review & merge it soon-ish, I'd say in the next 2 weeks.

@Thynix: To avoid discussions like the one we had recently: I'd still like to be considered maintainer of Freetalk, and thus deal with reviewing/mergeing stuff. Freetalk used to be my "actual" subproject before WOT performance grew so urgent that I had to suspend work on FT because people demanded WOT to be fixed ASAP.
(It  also needed the event-notifications API of WOT to be fix-able. I've discussed a lot with gerard on IRC and will guide him towards making Freetalk use event-notifications if he continues to be interested :)

**Comment by Thynix** [comment]
Understood.

**Comment by xor-freenet** [comment]
Sorry for ignoring this for so long. The WoT performance fixes seemed more important at the time.
However, now that I'm currently a volunteer until we have funding, I might change my priorities to "sometimes just do what is fun, even if it is not important" and this could mean I resume Freetalk maintenance. Ademan also has expressed his desire to see Freetalk compile at least, so this PR is the first thing I would do.
(Still, please don't get over-excited: Freetalk needs WoT to be very fast before it can become official again. So there will be WoT work on my primary focus as well. Also, getting Freetalk itself fast is some months of fulltime work...)

**Comment by xor-freenet** [comment]
Will work on merging this the following days/weeks.
First thought about review: Before adapting to purge-db4o (= what this PR does), it is critically important to have ```@Override``` annotations everywhere, for an explanation see https://bugs.freenetproject.org/view.php?id=6402
Branch issue-0006402-add-override-annotations has been started to check whether this is the case. I'll proceed to dealing with this PR after that branch is merged.

**Comment by xor-freenet** [comment]
I've started branch [issue-0006912-compilefix-for-purge-db4o]( https://github.com/freenet/plugin-Freetalk/tree/issue-0006912-compilefix-for-purge-db4o) to work on this.

It'll be done by walking through the commits of the similar WoT branch of issue [0006326](https://freenet.mantishub.io/view.php?id=6326) (was merged by https://github.com/freenet/plugin-WebOfTrust/commit/54c51436f3ea0b4a523c7a8c20b07d31beb785e3) and applying their concepts to Freetalk.
That's more easy for me than reviewing this as the necessary refactoring was done in individual atomic commits at WoT, one for each type of fred API change, instead of squashing them all into one.

However once I'm finished with that I'll review my resulting work against this PR so its efforts are not wasted :) I did also notice it provides some additional work such as a readme.md which I will consider for inclusion.

**Pull request closed without merging**
